Bug fixing
DeepCodeAI/tsc pull request #39
Opened 2020-12-28 20:13 UTC by Arvi3d

- better error handling related to local files;
- better handling of empty bundles;

2020-12-29 11:25 UTC, Spoor2709 approved these changes

2020-12-29 11:31 UTC, Spoor2709 requested changes
We should write tests for the outputs given a no bundle files and given something with no issues on the files, and on the git side the same. I know this is not very well explained so lets have a quick zoom 😃

2020-12-29 13:44 UTC, Arvi3d commented
@Spoor2709 please review again, I added tests.

2020-12-29 13:59 UTC, Spoor2709 approved these changes
Great Job

2020-12-29 14:00 UTC, merged

2021-01-28 16:24 UTC, snyksec commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@snyk/code-client/v/2.1.0)
- [GitHub release](https://github.com/snyk/code-client/releases/tag/v2.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: